In [8]:
a=['apple','organge','kiwi','grape','cherry']
print(a[4])
print(a[1:3])
print(a[:3])
print(a[2:])

cherry
['organge', 'kiwi']
['apple', 'organge', 'kiwi']
['kiwi', 'grape', 'cherry']


In [2]:
b=[['apple', 2], ['orange', 5], ['kiwi', 4], ['grape', 3], ['cherry',
25]]
print(b[2][1])

4


In [9]:

c=a.append('peach')
print(c)
print(a)
a.remove('kiwi')
print(a)

None
['apple', 'organge', 'kiwi', 'grape', 'cherry', 'peach']
['apple', 'organge', 'grape', 'cherry', 'peach']


In [10]:
d = [5, -2, 7, 3, -4, 10]
d_new=['p'if i>0 else 'n' for i in d if i<9]
print(d_new)

['p', 'n', 'p', 'p', 'n']


In [11]:
[print(i) for i in d]

5
-2
7
3
-4
10


[None, None, None, None, None, None]

In [12]:
for i in d:
    print(i)

5
-2
7
3
-4
10


In [13]:
for i in range (len(d)):
    print (f'the number at index of {i} is {d[i]}')

the number at index of 0 is 5
the number at index of 1 is -2
the number at index of 2 is 7
the number at index of 3 is 3
the number at index of 4 is -4
the number at index of 5 is 10


In [14]:
import numpy as np
np.__version__


'1.18.1'

In [15]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [16]:
np.array([3.14,4,2,5,3])


array([3.14, 4.  , 2.  , 5.  , 3.  ])

In [17]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [18]:
np.array([1,3,4.5,'hey'])

array(['1', '3', '4.5', 'hey'], dtype='<U32')

In [19]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [24]:
np.arange(0,10,1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.random.random((4,4))

array([[0.36442969, 0.46019497, 0.16148251, 0.33508055],
       [0.43170554, 0.8332971 , 0.90735954, 0.84787143],
       [0.55758024, 0.98945073, 0.6032537 , 0.6113343 ],
       [0.94568073, 0.72601959, 0.34191492, 0.56381285]])

In [29]:
np.random.randint(0, 5, (3, 3))

array([[2, 2, 0],
       [3, 4, 4],
       [0, 4, 1]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.seed(0)

In [39]:
x3=np.random.randint(10,size=(3,4,5))
x3

array([[[5, 7, 8, 8, 9],
        [2, 8, 6, 6, 9],
        [1, 6, 8, 8, 3],
        [2, 3, 6, 3, 6]],

       [[5, 7, 0, 8, 4],
        [6, 5, 8, 2, 3],
        [9, 7, 5, 3, 4],
        [5, 3, 3, 7, 9]],

       [[9, 9, 7, 3, 2],
        [3, 9, 7, 7, 5],
        [1, 2, 2, 8, 1],
        [5, 8, 4, 0, 2]]])

In [36]:
x2=np.random.randint(10,size=(5,5))
x2

array([[2, 8, 4, 3, 0],
       [4, 3, 6, 9, 8],
       [0, 8, 5, 9, 0],
       [9, 6, 5, 3, 1],
       [8, 0, 4, 9, 6]])

In [40]:
x3[2,:,3]

array([3, 7, 8, 0])

In [42]:
a=[1,2]
b=a[1]
b=4
print(a)
print(b)

[1, 2]
4


In [47]:
a=np.array([1,2,3])
b=a[1:2]
b[0]=4
print(a)
print(b)

[1 4 3]
[4]
